kind: Service
apiVersion: v1
metadata:
  labels:
    service.name: api
  name: api
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 3500
    targetPort: 3500
  selector:
    service.name: api
