kind: Service
apiVersion: v1
metadata:
  labels:
    service.name: integration
  name: integration
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 80
    targetPort: 3600
  selector:
    service.name: integration
